name: nc-news CI

on:
    push:
        branches: [main]

jobs:
    test_push_request:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test
