name: nc-news CI

on:
    push:
        branches: [main]

jobs:
    test_push_request:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 18

            - name: Use PostgreSQL
              uses: harmon758/postgresql-action@v1
              with:
                  postgresql db: "my_db"
                  postgresql user: "test_user"
                  postgresql password: "test_password"

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: PGDATABASE=my_db PGUSER=test_user PGPASSWORD=test_password npm test
